# Generated by Django 5.2.4 on 2025-10-01 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('common_law', 'Common Law')], max_length=20)),
                ('nationality', models.CharField(default='Jamaican', max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_address', models.TextField(blank=True)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('hours_per_week', models.PositiveIntegerField(default=40)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('probation_months', models.PositiveIntegerField(default=3)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('base_salary_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_currency', models.CharField(default='JMD', max_length=3)),
                ('salary_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('overtime_eligible', models.BooleanField(default=True)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('trn', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='TRN must be exactly 9 digits', regex='^\\d{9}$')])),
                ('nis', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='NIS must be exactly 9 digits', regex='^\\d{9}$')])),
                ('tax_status', models.CharField(choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately'), ('head_of_household', 'Head of Household')], default='single', max_length=20)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('education_credit', models.BooleanField(default=False)),
                ('pension_contribution_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('checking', 'Checking')], max_length=20)),
                ('vacation_days_entitlement', models.PositiveIntegerField(default=14)),
                ('vacation_days_used', models.PositiveIntegerField(default=0)),
                ('sick_days_entitlement', models.PositiveIntegerField(default=10)),
                ('sick_days_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('termination_type', models.CharField(blank=True, choices=[('voluntary', 'Voluntary'), ('involuntary', 'Involuntary'), ('retirement', 'Retirement'), ('end_of_contract', 'End of Contract')], max_length=20)),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True)),
                ('final_pay_date', models.DateField(blank=True, null=True)),
                ('exit_interview_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('transport', 'Transport'), ('meal', 'Meal'), ('housing', 'Housing'), ('communication', 'Communication'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('health_insurance', 'Health Insurance'), ('dental', 'Dental'), ('vision', 'Vision'), ('life_insurance', 'Life Insurance'), ('pension', 'Pension'), ('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('coverage', models.CharField(blank=True, max_length=200)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('suspension', 'Suspension'), ('termination', 'Termination')], max_length=20)),
                ('reason', models.TextField()),
                ('action_date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='employees.employee')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_disciplinary_actions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('tax_form', 'Tax Form'), ('bank_form', 'Bank Form'), ('id_copy', 'ID Copy'), ('resume', 'Resume'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick'), ('personal', 'Personal'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('bereavement', 'Bereavement'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeeleaverequest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='employees.employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='employees_e_user_id_a18cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business'], name='employees_e_busines_037e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['trn'], name='employees_e_trn_29d276_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['nis'], name='employees_e_nis_bc2b45_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('business', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('employee', 'day')},
        ),
    ]
