# Generated by Django 5.2.4 on 2025-10-01 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('trn', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='TRN must be exactly 9 digits', regex='^\\d{9}$')])),
                ('nis', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='NIS must be exactly 9 digits', regex='^\\d{9}$')])),
                ('business_type', models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Limited Liability Company', 'Limited Liability Company'), ('Corporation', 'Corporation'), ('Non-Profit Organization', 'Non-Profit Organization'), ('Cooperative', 'Cooperative'), ('Other', 'Other')], max_length=30)),
                ('industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Mining', 'Mining'), ('Manufacturing', 'Manufacturing'), ('Construction', 'Construction'), ('Retail Trade', 'Retail Trade'), ('Wholesale Trade', 'Wholesale Trade'), ('Transportation', 'Transportation'), ('Information Technology', 'Information Technology'), ('Finance and Insurance', 'Finance and Insurance'), ('Real Estate', 'Real Estate'), ('Professional Services', 'Professional Services'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Entertainment', 'Entertainment'), ('Government', 'Government'), ('Other', 'Other')], max_length=30)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('parish', models.CharField(choices=[('Kingston', 'Kingston'), ('St. Andrew', 'St. Andrew'), ('St. Thomas', 'St. Thomas'), ('Portland', 'Portland'), ('St. Mary', 'St. Mary'), ('St. Ann', 'St. Ann'), ('Trelawny', 'Trelawny'), ('St. James', 'St. James'), ('Hanover', 'Hanover'), ('Westmoreland', 'Westmoreland'), ('St. Elizabeth', 'St. Elizabeth'), ('Manchester', 'Manchester'), ('Clarendon', 'Clarendon'), ('St. Catherine', 'St. Catherine')], max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='Jamaica', max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('last_billing_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pay_period', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('pay_day', models.PositiveIntegerField(default=28)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('public_holiday_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('paye_registered', models.BooleanField(default=False)),
                ('nis_registered', models.BooleanField(default=False)),
                ('education_tax_registered', models.BooleanField(default=False)),
                ('heart_trust_registered', models.BooleanField(default=False)),
                ('gct_registered', models.BooleanField(default=False)),
                ('tax_year', models.PositiveIntegerField(default=2024)),
                ('fiscal_year_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='JMD', max_length=3)),
                ('timezone', models.CharField(default='America/Jamaica', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner'], name='businesses__owner_i_7abb69_idx'), models.Index(fields=['trn'], name='businesses__trn_ad35a3_idx'), models.Index(fields=['registration_number'], name='businesses__registr_9348f6_idx'), models.Index(fields=['subscription_status'], name='businesses__subscri_428733_idx'), models.Index(fields=['is_active'], name='businesses__is_acti_e70536_idx')],
            },
        ),
    ]
