# Generated by Django 4.2.7 on 2025-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_name_business_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['business_name']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='business_owner_i_ea9f33_idx',
            old_name='businesses__owner_i_7abb69_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='business_trn_f15e43_idx',
            old_name='businesses__trn_ad35a3_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='business_registr_1f1e0d_idx',
            old_name='businesses__registr_9348f6_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='business_subscri_8c0d63_idx',
            old_name='businesses__subscri_428733_idx',
        ),
        migrations.RenameIndex(
            model_name='business',
            new_name='business_is_acti_1f880e_idx',
            old_name='businesses__is_acti_e70536_idx',
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Mining', 'Mining'), ('Manufacturing', 'Manufacturing'), ('Construction', 'Construction'), ('Retail Trade', 'Retail Trade'), ('Wholesale Trade', 'Wholesale Trade'), ('Transportation', 'Transportation'), ('Information Technology', 'Information Technology'), ('Finance and Insurance', 'Finance and Insurance'), ('Real Estate', 'Real Estate'), ('Professional Services', 'Professional Services'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Entertainment', 'Entertainment'), ('Media', 'Media'), ('Government', 'Government'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='business',
            table='business',
        ),
    ]
