# Generated by Django 4.2.7 on 2025-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_fix_fiscal_year_end_null'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_business_per_owner'),
        ),
    ]
