# Generated by Django 4.2.7 on 2025-10-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_add_unique_business_per_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_business_per_owner',
        ),
    ]
