# Generated by Django 5.2.4 on 2025-10-01 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_timestamp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nis',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='NIS must be exactly 9 digits', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='trn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='TRN must be exactly 9 digits', regex='^\\d{9}$')]),
        ),
    ]
