# Generated by Django 4.2.25 on 2026-02-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_nis_alter_user_trn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_business_id',
        ),
    ]
