# Generated by Django 5.2.4 on 2025-10-01 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('pay_period_type', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('back_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sick_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vacation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unpaid_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paye_taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('paye_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=5)),
                ('education_tax_rate', models.DecimalField(decimal_places=4, default=0.025, max_digits=5)),
                ('education_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('heart_trust_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=5)),
                ('heart_trust_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_employee_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('pension_employer_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('pension_employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('mobile_payment', 'Mobile Payment')], default='bank_transfer', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('check_number', models.CharField(blank=True, max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('personal_allowance', models.DecimalField(decimal_places=2, default=1500000, max_digits=12)),
                ('paye_threshold', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('education_tax_threshold', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pay_period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('transport', 'Transport'), ('meal', 'Meal'), ('housing', 'Housing'), ('communication', 'Communication'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('loan_repayment', 'Loan Repayment'), ('union_dues', 'Union Dues'), ('insurance', 'Insurance'), ('garnishment', 'Garnishment'), ('advance', 'Advance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('recurring', models.BooleanField(default=False)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_deductions', to='payroll.payroll')),
            ],
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['business', 'pay_period_start'], name='payroll_pay_busines_83e4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'pay_period_start'], name='payroll_pay_employe_c67df7_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payroll_number'], name='payroll_pay_payroll_77eef1_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['pay_date'], name='payroll_pay_pay_dat_008cf5_idx'),
        ),
    ]
