# Generated by Django 4.2.7 on 2025-12-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = []
