# Generated by Django 4.2.7 on 2025-12-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_auto_20251210_1317"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Fresh installs use payroll_payroll before migration 0004 renames table to payroll.
            -- Guard constraint creation so reruns do not fail.
            ALTER TABLE payroll_payroll DROP CONSTRAINT IF EXISTS payroll_employee_id_67de6c80_fk_employee_id;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'payroll_employee_id_fk_employees_employee_id'
                ) THEN
                    ALTER TABLE payroll_payroll
                    ADD CONSTRAINT payroll_employee_id_fk_employees_employee_id
                    FOREIGN KEY (employee_id) REFERENCES employees_employee(id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Reverse migration: remove custom FK and optionally restore legacy FK if employee table exists.
            ALTER TABLE payroll_payroll DROP CONSTRAINT IF EXISTS payroll_employee_id_fk_employees_employee_id;

            DO $$
            BEGIN
                IF to_regclass('public.employee') IS NOT NULL
                   AND NOT EXISTS (
                       SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'payroll_employee_id_67de6c80_fk_employee_id'
                   ) THEN
                    ALTER TABLE payroll_payroll
                    ADD CONSTRAINT payroll_employee_id_67de6c80_fk_employee_id
                    FOREIGN KEY (employee_id) REFERENCES employee(id);
                END IF;
            END $$;
            """
        )
    ]
