# Generated by Django 4.2.25 on 2026-02-22 01:27

from django.db import migrations, connection


def rename_index_if_exists(old_name, new_name):
    def _rename(apps, schema_editor):
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(
                f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";'
            )

    return _rename


def alter_table_if_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass('payroll_payroll');")
        result = cursor.fetchone()
        if result and result[0]:
            schema_editor.alter_db_table('payroll_payroll', 'payroll')

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20251211_0919'),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists('payroll_pay_busines_83e4d7_idx', 'payroll_busines_088421_idx'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists('payroll_pay_employe_c67df7_idx', 'payroll_employe_b85f62_idx'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists('payroll_pay_payroll_77eef1_idx', 'payroll_payroll_24a73d_idx'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists('payroll_pay_status_465a76_idx', 'payroll_status_ac0f6a_idx'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists('payroll_pay_pay_dat_008cf5_idx', 'payroll_pay_dat_300674_idx'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            alter_table_if_exists,
            migrations.RunPython.noop,
        ),
    ]
