# Generated by Django 4.2.25 on 2026-02-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20251211_0919'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payroll',
            new_name='payroll_busines_088421_idx',
            old_name='payroll_pay_busines_83e4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='payroll_employe_b85f62_idx',
            old_name='payroll_pay_employe_c67df7_idx',
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='payroll_payroll_24a73d_idx',
            old_name='payroll_pay_payroll_77eef1_idx',
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='payroll_status_ac0f6a_idx',
            old_name='payroll_pay_status_465a76_idx',
        ),
        migrations.RenameIndex(
            model_name='payroll',
            new_name='payroll_pay_dat_300674_idx',
            old_name='payroll_pay_pay_dat_008cf5_idx',
        ),
        migrations.AlterModelTable(
            name='payroll',
            table='payroll',
        ),
    ]
