# Generated by Django 5.2.4 on 2025-10-01 15:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='JMD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_processor_id', models.CharField(blank=True, max_length=100)),
                ('max_employees', models.IntegerField(default=10)),
                ('max_businesses', models.IntegerField(default=1)),
                ('max_transactions_per_month', models.IntegerField(default=100)),
                ('max_payroll_runs_per_month', models.IntegerField(default=4)),
                ('has_payroll', models.BooleanField(default=True)),
                ('has_financial_reporting', models.BooleanField(default=True)),
                ('has_tax_calculations', models.BooleanField(default=True)),
                ('has_multi_user_access', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('current_employees', models.IntegerField(default=0)),
                ('current_businesses', models.IntegerField(default=1)),
                ('transactions_this_month', models.IntegerField(default=0)),
                ('payroll_runs_this_month', models.IntegerField(default=0)),
                ('last_usage_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='JMD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_processor_response', models.JSONField(blank=True, default=dict)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('payment_failed', 'Payment Failed'), ('payment_succeeded', 'Payment Succeeded')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name_plural': 'Subscription histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['business'], name='subscriptio_busines_2d4e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_billing_date'], name='subscriptio_next_bi_0e9626_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_type'], name='subscriptio_plan_ty_67947e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_a82d94_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['transaction_id'], name='subscriptio_transac_ef3e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_date'], name='subscriptio_payment_a833d5_idx'),
        ),
    ]
