# Generated by Django 4.2.7 on 2025-10-11 23:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, unique=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=100)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('captured', 'Captured'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('intent', models.CharField(choices=[('capture', 'Capture'), ('authorize', 'Authorize')], default='capture', max_length=20)),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=20)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('paypal_create_response', models.JSONField(blank=True, default=dict)),
                ('paypal_capture_response', models.JSONField(blank=True, default=dict)),
                ('paypal_webhook_data', models.JSONField(blank=True, default=dict)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_name', models.CharField(blank=True, max_length=100)),
                ('payer_country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('PAYMENT.CAPTURE.COMPLETED', 'Payment Capture Completed'), ('PAYMENT.CAPTURE.DENIED', 'Payment Capture Denied'), ('PAYMENT.CAPTURE.PENDING', 'Payment Capture Pending'), ('PAYMENT.CAPTURE.REFUNDED', 'Payment Capture Refunded'), ('CHECKOUT.ORDER.APPROVED', 'Checkout Order Approved'), ('CHECKOUT.ORDER.COMPLETED', 'Checkout Order Completed'), ('BILLING.SUBSCRIPTION.CREATED', 'Billing Subscription Created'), ('BILLING.SUBSCRIPTION.CANCELLED', 'Billing Subscription Cancelled')], max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('webhook_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paypalpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook_id'], name='subscriptio_webhook_cb7932_idx'), models.Index(fields=['event_type', 'processed'], name='subscriptio_event_t_f5c8ff_idx'), models.Index(fields=['resource_id'], name='subscriptio_resourc_3c9271_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paypalpayment',
            index=models.Index(fields=['paypal_order_id'], name='subscriptio_paypal__275b99_idx'),
        ),
        migrations.AddIndex(
            model_name='paypalpayment',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_368279_idx'),
        ),
        migrations.AddIndex(
            model_name='paypalpayment',
            index=models.Index(fields=['status', 'created_at'], name='subscriptio_status_b9c864_idx'),
        ),
    ]
